-- DROP DATABASE IF EXISTS employeeTrackerDB;

-- CREATE DATABASE employeeTrackerDB;

USE employeeTrackerDB;

DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS employee;

CREATE TABLE roles (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    title VARCHAR(30) NOT NULL,
    salary DECIMAL NOT NULL,
    department_id INTEGER NOT NULL
);

CREATE TABLE employee (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  roles_id INTEGER UNSIGNED,
  manager_id INTEGER UNSIGNED,
  CONSTRAINT fk_roles FOREIGN KEY (roles_id) REFERENCES roles(id) ON DELETE SET NULL
);

